config/routes.rb
Rails.application.routes.draw do
  scope "/bewerbung/projekt-upload" do
    resources :settings
    devise_for :users, :controllers => {registrations: 'registrations'}

    resources :users, only: [:index, :show, :edit, :update] do
      resources :assets
      get 'reopen', to: 'users#reopen'
    end

    resources :majors
    resources :settings

    get 'admin', to: 'admin#home'
    get 'admin/download', to: 'admin#download'

    root to: 'pages#home'
  end
end

app/models/major.rb
class Major < ApplicationRecord

  has_many :users

  def to_s
    "Name: #{name}"
  end

end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  load_and_authorize_resource

  before_action :set_major, only: [:show, :edit, :update, :destroy]

  # GET /majors
  # GET /majors.json
  def index
    @majors = Major.all
  end

  # GET /majors/1
  # GET /majors/1.json
  def show
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors
  # POST /majors.json
  def create
    @major = Major.new(major_params)

    respond_to do |format|
      if @major.save
        format.html { redirect_to @major, notice: 'Major was successfully created.' }
        format.json { render :show, status: :created, location: @major }
      else
        format.html { render :new }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majors/1
  # PATCH/PUT /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to @major, notice: 'Major was successfully updated.' }
        format.json { render :show, status: :ok, location: @major }
      else
        format.html { render :edit }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majors/1
  # DELETE /majors/1.json
  def destroy
    @major.destroy
    respond_to do |format|
      format.html { redirect_to majors_url, notice: 'Major was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_major
    @major = Major.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def major_params
    params.fetch(:major, {}).permit(:name)
  end
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/views/majors/_audio.html.erb
<%= render partial: 'assets/form', locals: {user: @user, tag: 'cv', title: 'Lebenslauf', id: 'cv'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'audio', title: 'Tondokument 1', id: 'audio1'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'audio', title: 'Tondokument 2', id: 'audio2'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'concept', title: 'Konzept', id: 'concept'} %>

app/views/majors/_computeranimation.html.erb
<%= render partial: 'assets/form', locals: {user: @user, tag: 'cv', title: 'Lebenslauf', id: 'cv'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'movie', title: 'Animationsfilm', id: 'movie'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'sketch', title: 'Skizze', id: 'sketch'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'concept', title: 'Konzept', id: 'concept'} %>

app/views/majors/_film.html.erb
<%= render partial: 'assets/form', locals: {user: @user, tag: 'cv', title: 'Lebenslauf', id: 'cv'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'movie', title: 'Film', id: 'movie'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'image', title: 'Foto 1*', id: 'image1'} %>
<small class="text-muted">Foto 1 ist verpflichtend.</small>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'image', title: 'Foto 2*', id: 'image2'} %>
<small class="text-muted">Foto 2 ist verpflichtend.</small>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'image', title: 'Foto 3', id: 'image3'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'image', title: 'Foto 4', id: 'image4'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'image', title: 'Foto 5', id: 'image5'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'image', title: 'Foto 6', id: 'image6'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'image', title: 'Foto 7', id: 'image7'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'concept', title: 'Beschreibung', id: 'concept'} %>

app/views/majors/_form.html.erb
<%= form_for(major) do |f| %>

    <% if major.errors.any? %>
        <div id="error_explanation" class="alert-danger">
          <h2><%= pluralize(major.errors.count, "error") %> prohibited this major from being saved:</h2>
          <ul>
            <% major.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.text_field :name %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/majors/_mediendesign.html.erb
<%= render partial: 'assets/form', locals: {user: @user, tag: 'cv', title: 'Lebenslauf', id: 'cv'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'movie', title: 'Animationsfilm', id: 'movie'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'sketch', title: 'Skizze', id: 'sketch'} %>
<br>
<%= render partial: 'assets/form', locals: {user: @user, tag: 'concept', title: 'Konzept', id: 'concept'} %>

app/views/majors/edit.html.erb
<h1>Editing Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Show', @major %> |
<%= link_to 'Back', majors_path %>

app/views/majors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Majors</h1>

<table class="table table-responsive table-hover table-striped table-sm">
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @majors.each do |major| %>
      <tr>
        <td><%= major %></td>
        <td><%= link_to 'Show', major %></td>
        <td><%= link_to 'Edit', edit_major_path(major) %></td>
        <td><%= link_to 'Destroy', major, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Major', new_major_path %>

app/views/majors/new.html.erb
<h1>New Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Back', majors_path %>

app/views/majors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_major_path(@major) %> |
<%= link_to 'Back', majors_path %>