config/routes.rb
Rails.application.routes.draw do
  scope "/bewerbung/projekt-upload" do
    resources :settings
    devise_for :users, :controllers => {registrations: 'registrations'}

    resources :users, only: [:index, :show, :edit, :update] do
      resources :assets
      get 'reopen', to: 'users#reopen'
    end

    resources :majors
    resources :settings

    get 'admin', to: 'admin#home'
    get 'admin/download', to: 'admin#download'

    root to: 'pages#home'
  end
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user

  Paperclip.interpolates :user_name do |attachment, styles|
    attachment.instance.user.email
  end

  has_attached_file :file, path: ':rails_root/public/system/:user_name/:filename', url: '/system/:user_name/:filename'
  validates :file, attachment_presence: true
  validates_with AttachmentSizeValidator, attributes: :file, less_than: 1.gigabytes
  do_not_validate_attachment_file_type :file

  enum type: [:cv, :movie, :audio, :image, :concept, :sketch, :storyboard]

  def to_s
    "Asset: #{id} → #{file_file_name}"
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  include ActionController::Streaming
  include Zipline

  load_and_authorize_resource :user
  load_and_authorize_resource :asset, :through => :user

  before_action :set_user
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /users/:user_id/assets
  # GET /users/:user_id/assets.json
  def index
    @assets = @user.assets

    respond_to do |format|
      format.html
      format.json
      format.zip do
        id = "#{@user.last_name.parameterize.upcase}_#{@user.first_name.parameterize}_#{@user.major.name.parameterize}_#{@user.email.parameterize}"
        files = @user.assets.map do |asset|
          [File.open(asset.file.path), "#{@user.major.name.parameterize}/#{id}/#{asset.file_file_name}"]
        end
        zipline(files, "#{id}.zip")
      end
    end
  end

  # GET /users/:user_id/assets/1
  # GET /users/:user_id/assets/1.json
  def show
  end

  # GET /users/:user_id/assets/new
  def new
    @asset = Asset.new
  end

  # GET /users/:user_id/assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = @user.assets.new(asset_params)

    respond_to do |format|
      if @asset.save
        format.html {
          @assets = @user.assets
          render :layout => false
        }
        format.json { render :show, status: :created, location: [@user, @asset] }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to user_url(@user), notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: [@user, @asset] }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to user_url(@user), notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_asset
    @asset = Asset.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def asset_params
    params.require(:asset).permit(:user_id, :file, :tag)
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<h4><%= title %></h4>
<%= form_for [user, Asset.new(tag: tag)], url: user_assets_path(user, Asset.new(tag: tag), format: 'html'), html: {id: id, multipart: true, class: 'dropzone'} do |f| %>
    <%= f.hidden_field :tag %>
    <div class="fallback form-group">
      <%= f.file_field :file, {class: 'form-control'} %><br>
      <%= f.submit 'Upload', {class: 'btn btn-primary'} %>
    </div>
<% end %>

app/views/assets/_index.html.erb
<% if assets.length == 0 %>
    <p class="text-muted">Du hast noch nichts hochgeladen.</p>
<% else %>
    <table class="table table-striped table-sm">
      <thead>
      <tr>
        <th>Datei</th>
        <th>Typ</th>
        <% if can? :destroy, [user, assets] %>
            <th></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <% assets.each do |asset| %>
          <tr>
            <td><%= link_to "#{asset.file_file_name}", asset.file.url %></td>
            <td><span class="text-muted text-uppercase"><%= asset.tag %></span></td>
            <% if can? :destroy, user => asset %>
                <td class="text-right">
                  <%= link_to 'Destroy', [user, asset], method: :delete, data: {confirm: 'Are you sure?'} %>
                </td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/assets/create.html.erb
<%= render partial: 'assets/index', locals: {user: @user, assets: @assets} %>

app/views/assets/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Show', user_asset_path(@asset.user, @asset) %> |
<%= link_to 'Back', user_assets_path(@asset.user) %>

app/views/assets/index.html.erb
<h1>Files</h1>

<table class="table table-responsive table-hover table-striped table-sm">
  <thead>
  <tr>
    <th>#ID</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render partial: 'index', locals: {user: @user, assets: @user.assets} %>
  </tbody>
</table>

<hr class="my-3">

<%= link_to 'New Asset', new_user_asset_path %>

app/views/assets/new.html.erb
<h1>New Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Back', user_assets_path(@user) %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asset:</strong>
  <%= @asset %>
</p>

<%= link_to 'Edit', edit_user_asset_path(@asset.user, @asset) %> |
<%= link_to 'Back', user_assets_path(@user) %>